//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logic.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string ApplicationModelBirthDate {
            get {
                return ResourceManager.GetString("ApplicationModelBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ApplicationModelCity {
            get {
                return ResourceManager.GetString("ApplicationModelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ApplicationModelCountry {
            get {
                return ResourceManager.GetString("ApplicationModelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ApplicationModelEmail {
            get {
                return ResourceManager.GetString("ApplicationModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string ApplicationModelEmailInvalid {
            get {
                return ResourceManager.GetString("ApplicationModelEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency in english.
        /// </summary>
        public static string ApplicationModelEnglishLevel {
            get {
                return ResourceManager.GetString("ApplicationModelEnglishLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal status.
        /// </summary>
        public static string ApplicationModelLegalStatus {
            get {
                return ResourceManager.GetString("ApplicationModelLegalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write about your experience in projects pertaining or directly related to the subject of the workshop.
        /// </summary>
        public static string ApplicationModelMotivation1 {
            get {
                return ResourceManager.GetString("ApplicationModelMotivation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you previously participated in similar workshops. If so, when and where?.
        /// </summary>
        public static string ApplicationModelMotivation2 {
            get {
                return ResourceManager.GetString("ApplicationModelMotivation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What motivates you to apply for participation in the workshop?.
        /// </summary>
        public static string ApplicationModelMotivation3 {
            get {
                return ResourceManager.GetString("ApplicationModelMotivation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you plan to use the experience gained in the workshop?.
        /// </summary>
        public static string ApplicationModelMotivation4 {
            get {
                return ResourceManager.GetString("ApplicationModelMotivation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you expectations from the workshop?.
        /// </summary>
        public static string ApplicationModelMotivation5 {
            get {
                return ResourceManager.GetString("ApplicationModelMotivation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did you find out about the workshop?.
        /// </summary>
        public static string ApplicationModelMotivation6 {
            get {
                return ResourceManager.GetString("ApplicationModelMotivation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ApplicationModelName {
            get {
                return ResourceManager.GetString("ApplicationModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the organization.
        /// </summary>
        public static string ApplicationModelOrganizationInfo {
            get {
                return ResourceManager.GetString("ApplicationModelOrganizationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string ApplicationModelOrganizationName {
            get {
                return ResourceManager.GetString("ApplicationModelOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of participants.
        /// </summary>
        public static string ApplicationModelParticipantsNumber {
            get {
                return ResourceManager.GetString("ApplicationModelParticipantsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ApplicationModelPhone {
            get {
                return ResourceManager.GetString("ApplicationModelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to data processing.
        /// </summary>
        public static string ApplicationModelProcessData {
            get {
                return ResourceManager.GetString("ApplicationModelProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string ApplicationModelProfession {
            get {
                return ResourceManager.GetString("ApplicationModelProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ApplicationModelRequiredField {
            get {
                return ResourceManager.GetString("ApplicationModelRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vk or facebook url.
        /// </summary>
        public static string ApplicationModelSocialNetworkUrl {
            get {
                return ResourceManager.GetString("ApplicationModelSocialNetworkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ApplicationModelSurname {
            get {
                return ResourceManager.GetString("ApplicationModelSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid url.
        /// </summary>
        public static string ApplicationModelUrlInvalid {
            get {
                return ResourceManager.GetString("ApplicationModelUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why are you interested in becoming a volunteer of the workshop?.
        /// </summary>
        public static string ApplicationModelVolunteeringMotivation {
            get {
                return ResourceManager.GetString("ApplicationModelVolunteeringMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days and times in which you can be present.
        /// </summary>
        public static string ApplicationModelWorkTimeRange {
            get {
                return ResourceManager.GetString("ApplicationModelWorkTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid date format.
        /// </summary>
        public static string DateTimeInvalid {
            get {
                return ResourceManager.GetString("DateTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string EnglishLevel_Advanced {
            get {
                return ResourceManager.GetString("EnglishLevel_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary.
        /// </summary>
        public static string EnglishLevel_Elementary {
            get {
                return ResourceManager.GetString("EnglishLevel_Elementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string EnglishLevel_Intermediate {
            get {
                return ResourceManager.GetString("EnglishLevel_Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-intermediate.
        /// </summary>
        public static string EnglishLevel_PreIntermediate {
            get {
                return ResourceManager.GetString("EnglishLevel_PreIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper-intermediate.
        /// </summary>
        public static string EnglishLevel_UpperIntermediate {
            get {
                return ResourceManager.GetString("EnglishLevel_UpperIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered initiative.
        /// </summary>
        public static string LegalStatus_NotRegisteredInitiative {
            get {
                return ResourceManager.GetString("LegalStatus_NotRegisteredInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string LegalStatus_Other {
            get {
                return ResourceManager.GetString("LegalStatus_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public organization.
        /// </summary>
        public static string LegalStatus_PublicOrganization {
            get {
                return ResourceManager.GetString("LegalStatus_PublicOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the fields marked in red.
        /// </summary>
        public static string WorkShopApplicationErrors {
            get {
                return ResourceManager.GetString("WorkShopApplicationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation.
        /// </summary>
        public static string WorkShopApplicationMotivation {
            get {
                return ResourceManager.GetString("WorkShopApplicationMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string WorkShopApplicationPersonalData {
            get {
                return ResourceManager.GetString("WorkShopApplicationPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is received. Thank you for registration!.
        /// </summary>
        public static string WorkShopApplicationReceived {
            get {
                return ResourceManager.GetString("WorkShopApplicationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string WorkShopApplicationSubmit {
            get {
                return ResourceManager.GetString("WorkShopApplicationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application for the first day of workshop &quot;Regeneration of industrial buildings in Ukraine&quot;, which will be held at Jam Factory September 24 from 14:00 to 20:00, successfully accepted. Your number - {0}. Read more about the program &lt;a href=&quot;http://culture.in.ua/en/projects/regeneration-of-industrial-buildings/program/&quot;&gt;here&lt;/a&gt;. Thank you for registration!.
        /// </summary>
        public static string WorkShopFirstDayApplicationEmailBody {
            get {
                return ResourceManager.GetString("WorkShopFirstDayApplicationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration for the first day of workshop.
        /// </summary>
        public static string WorkShopFirstDayApplicationEmailSubject {
            get {
                return ResourceManager.GetString("WorkShopFirstDayApplicationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately number of places are limited. We can not register you..
        /// </summary>
        public static string WorkShopFirstDayApplicationLimitExceeded {
            get {
                return ResourceManager.GetString("WorkShopFirstDayApplicationLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the registration! Your application for the first day of workshop &quot;Regeneration of industrial buildings in Ukraine&quot; is received and we sent you the email with further info. Your number -  {0}. Please remember it, you will need to know it at the entrance to the event.
        /// </summary>
        public static string WorkShopFirstDayApplicationReceived {
            get {
                return ResourceManager.GetString("WorkShopFirstDayApplicationReceived", resourceCulture);
            }
        }
    }
}
